#cp -f rabbitmq.repo /etc/yum.repos.d/rabbitmq.repo
##dnf install rabbitmq-server -y
#systemctl enable rabbitmq-server
#systemctl start rabbitmq-server
#rabbitmqctl add_user roboshop roboshop123
#rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"

- name: copy repo file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: install rabbitmq-server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: start systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yml

- name: add user in rabbit-mq
  ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123 ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
