#cp -f rabbitmq.repo /etc/yum.repos.d/rabbitmq.repo
##dnf install rabbitmq-server -y
#systemctl enable rabbitmq-server
#systemctl start rabbitmq-server
#rabbitmqctl add_user roboshop roboshop123
#rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"

- name: copy repo file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: install rabbitmq-server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: systemd start
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    enabled: true
    state: restarted

- name: add user in rabbit-mq
  ansible.builtin.shell: rabbitmqctl add_user {{lookup('community.hashi_vault.hashi_vault','secret=roboshop-{{env}}/data/rabbitmq:ROOT_USER token={{token}} url=http://vault-internal.sdevops.shop:8200')}} {{lookup('community.hashi_vault.hashi_vault','secret roboshop-{{env}}/data/rabbitmq:ROOT_PASSWORD token={{token}} url=http://vault-internal.sdevops.shop:8200')}} ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
