- name: install python
  ansible.builtin.shell: dnf install python3 gcc python3-devel -y

- name: import pre req role
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq.yml

- name: install requirements using pip3
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app

- name: systemd start
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yml
