#dnf install mysql-server -y
#systemctl enable mysqld
#systemctl start mysqld
#mysql_secure_installation --set-root-pass RoboShop@1

- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: start mysqld
  ansible.builtin.systemd_service:
    name: mysqld
    enabled: yes
    state: restarted
    daemon_reload: true
- name: send user name and password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
#  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{lookup('community.hashi_vault.hashi_vault','secret=roboshop-{{env}}/data/mysql:ROOT_PASSWORD token={{token}} url=http://vault-internal.sdevops.shop:8200')}}
