#cp -f mongo.repo /etc/yum.repos.d/mongo.repo

#source common.sh
#component=catalogue
#NODEJS

#dnf install mongodb-mongosh -y
#mongosh --host mongodb-dev.sdevops.shop </app/db/master-data.js

- name: copy the repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: importing the nodejs from common role
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yml

- name: install mongodb
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

- name: connect mongodb to host
  ansible.builtin.shell: mongosh --host mongodb-dev.sdevops.shop </app/db/master-data.js
