# #cp -f mongo.repo /etc/yum.repos.d/mongo.repo

# #source common.sh
# #component=catalogue
# #NODEJS

# #dnf install mongodb-mongosh -y
# #mongosh --host mongodb-dev.sdevops.shop </app/db/master-data.js

# - name: copy the repo file
#   ansible.builtin.copy:
#     src: mongo.repo
#     dest: /etc/yum.repos.d/mongo.repo

# - name: importing the nodejs from common role
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: nodejs.yml

# - name: install mongodb
#   ansible.builtin.dnf:
#     name: mongodb-mongosh
#     state: installed

# - name: connect mongodb to host
#   ansible.builtin.shell: mongosh --host  mongodb-dev.sdevops.shop </app/db/master-data.js

- name: import docker
  ansbile.builtin.import_role:
    name: common
    tasks_from: docker

- name: Restart a container
  community.docker.docker_container:
    name: catalogue
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
    ports:
      - "8080:8080"
    env:
      MONGO: "{{lookup('community.hashi_vault.hashi_vault','secret=roboshop-{{env}}/data/catalogue:MONGO token={{token}} url=http://vault-internal.sdevops.shop:8200')}}"
      MONGO_URL: "{{lookup('community.hashi_vault.hashi_vault','secret=roboshop-{{env}}/data/catalogue:MONGO_URL token={{token}} url=http://vault-internal.sdevops.shop:8200')}}"
