#dnf install mysql-server -y
#systemctl enable mysqld
#systemctl start mysqld
#mysql_secure_installation --set-root-pass RoboShop@1

- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: start mysqld
  ansible.builtin.systemd_service:
    name: mysqld
    enabled: true
    state: restarted
    daemon_reload: true
- name: send user name and password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
