- name: Download hashicorp repo file
  ansible.builtin.copy:
    src: hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install vault using dnf
  ansible.builtin.dnf:
    name: vault
    state: installed
- name: Copy config
  ansible.builtin.copy:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl

- name: start service
  ansible.builtin.systemd_service:
    name: vault
    state: restarted
    enabled: yes
