- name: Download repo file
  ansible.builtin.copy:
    src: hashicorp.repo
    dest: /etc/yum.repos.d/vault.repo

- name: install vault
  ansible.builtin.dnf:
    name: vault
    state: installed

- name: copy the vault config
  ansible.builtin.copy:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl

- name: start service
  ansible.builtin.systemd_service:
    state: restarted
    enabled: yes
