- name: Add HashiCorp GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpm.releases.hashicorp.com/gpg

- name: Add hashicorp repo
  ansible.builtin.yum_repository:
    name: hashicorp
    description: HashiCorp Stable -$basearch
    baseurl: https"//rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    enabled: yes
    gpgcheck: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: install Vault
  ansible.builtin.yum:
    name: vault
    state: present
