- name: Add docker repo
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker.repo

- name: install docker
  ansible.builtin.dnf:
    name: docker-ce
    state: installed

- name: start docker
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: yes
