- name: install maven
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: import app_prereq from common
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq.yml

- name: install dependencies
  ansible.builtin.shell: mvn clean package; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: install mysql
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: connect schema from the hosts
  ansible.builtin.shell: mysql -h mysql-dev.sdevops.shop -uroot -p{{password}} < /app/db/schema.sql

- name: connect app-user from the hosts
  ansible.builtin.shell: mysql -h mysql-dev.sdevops.shop -uroot -p{{password}} < /app/db/app-user.sql

- name: connect master-data from the hosts
  ansible.builtin.shell: mysql -h mysql-dev.sdevops.shop -uroot -p{{password}} < /app/db/master-data.sql

- name: import systemd from common role
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yml
