#dnf module disable redis -y
#dnf module enable redis:7 -y
#dnf install redis -y
#sed -i 's|127.0.0.1|0.0.0.0|' /etc/redis/redis.conf
#systemctl enable redis
#systemctl start redis
- name: disable and enable redis
  ansible.builtin.shell: dnf module disable redis -y ; dnf module enable redis:7 -y

- name: install redis
  ansible.builtin.dnf:
    name: redis
    state: installed
- name: replace a ip address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 127.0.0.1
    replace: 0.0.0.0
- name: start redis service
  ansible.builtin.systemd_service:
    name: redis
    enabled: true
    daemon_reload: true
    state: restarted
